aws:
  region: "us-east-1"

secret:
  credential: "instagram_main"

dynamodb:
  table: "instagram_unfollowers"
  updateTable: "last_updated"
  updateTableKey: "instagram_unfollow_nonfollowers"
  logTable: "log"

app:
  name: "Instagram_unfollow_nonfollowers"
  environment: "production"
  logging_level: "info"
  grace_period_days: 7

instagram:
  lazy_load_time: 5000
  profile_unfollow_count: 50
  modal_selector:
    popup: ".x9f619.xjbqb8w.x78zum5.x168nmei.x13lgxp2.x5pf9jr.xo71vjh.x1n2onr6.x1plvlek.xryxfnj.x1iyjqo2.x2lwn1j.xeuugli.xdt5ytf.xqjyukv.x1qjc9v5.x1oa3qoh.x1nhvcw1"
    scroll: ".xyi19xy.x1ccrb07.xtf3nb5.x1pc53ja.x1lliihq.x1iyjqo2.xs83m0k.xz65tgg.x1rife3k.x1n2onr6"
